backend:
  name: git-gateway
  repo: shaharbest/air-conditioner
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/5b0cdc16-fdc7-4702-8b0b-138bc51697af/pkce
  auth_token_endpoint: /sites/5b0cdc16-fdc7-4702-8b0b-138bc51697af/token
  gateway_url: https://gateway.decapbridge.com
  commit_messages:
    create: Create {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge

auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

logo_url: https://decapbridge.com/decapcms-with-bridge.svg
site_url: https://danielle.best

media_folder: static/images
public_folder: /images

collections:
  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    filter: { field: "draft", value: false }
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: true }
      - { label: "Sort Order", name: "weight", widget: "number", default: 1 }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "Contact Info"
        name: "contact"
        file: "data/contact.yaml"
        fields:
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Contact Button Link", name: "contact_button_link", widget: "string", default: "contact" }

      - label: "Features"
        name: "features"
        file: "data/features.json"
        fields:
          - label: "Features"
            name: "features"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }

      - label: "Homepage"
        name: "homepage"
        file: "content/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Meta Title", name: "meta_title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Hero Image", name: "intro_image", widget: "image", required: false }
          - { label: "Hero Image Absolute Position", name: "intro_image_absolute", widget: "boolean", default: true, required: false }
          - { label: "Hero Image Hide on Mobile", name: "intro_image_hide_on_mobile", widget: "boolean", default: true, required: false }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Contact Page"
        name: "contact_page"
        file: "content/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
